console.log('AAAAAAAAAAAAAAAAAAAAA')
console.log('           A        A')
console.log('           A        A')
console.log('           A        A')
console.log('           A        A')
console.log('           A        A')
console.log('AAAAAAAAAAAAAAAAAAAAA')
console.log('MMMMMMMMMMMMMMMMMMMMM')
console.log('                   M')
console.log('                 M')
console.log('               M')
console.log('             M')
console.log('               M')
console.log('                 M')
console.log('                   M')
console.log('MMMMMMMMMMMMMMMMMMMMM')

